### ISSUE TITLE
Replacing uses of copy.deepcopy with serialized approaches

### ISSUE THREAD

**Issue by a-vinod** [LLNL/Abmarl#190]
I profiled `abmarl train examples/hackathon_2021_summer/hunting_foraging_rl.py` (hackathon-2021-summer branch) with cProfile and noticed the scalability for the number of agents in the simulation could be improved by replacing usage of [copy.deepcopy()](https://docs.python.org/3/library/copy.html#copy.deepcopy) with a serialized approach, such as [pickle](https://docs.python.org/3/library/pickle.html).

Here are the instances of copy.py in the profile:
![image](https://user-images.githubusercontent.com/56094467/129420656-5d2148bf-7757-462f-855b-0259b2971f94.png)

And [here](https://stackoverflow.com/questions/1410615/copy-deepcopy-vs-pickle)'s a stack post with a simple one-on-one comparison of the performance difference between the two for deep copying python dictionaries. I ran my own experiment to see how it would scale and it looks like this is something worthwhile to pursue:
![output](https://user-images.githubusercontent.com/56094467/129422188-6aaf86d6-887f-4596-9ced-98243356d4e2.gif)

**Comment by rusu24edward** [comment]
The answer to the linked stack overflow post indicates that using pickle will restrict the design options, so deepcopy is typically a better choice because it is more general, even though it is slower.

There is some redundancy in the FlattenActionWrapper where it makes a deep copy of the agents. It's super class, Wrapper, already does this, so we essentially do it twice. We can remove that.
