### ISSUE TITLE
Allow OrderedDict agents

### ISSUE THREAD

**Issue by aowen87** [LLNL/Abmarl#507]
It looks like Abmarl expects agents to be of type dict and not OrderedDict:

```
  File "/usr/WS2/maguire7/toss_4_jcats/decsup/src/jcats/bridge/policyBridge/abmarl_jcats_env.py", line 72, in __init__
    self.agents       = agents
  File "/usr/WS2/maguire7/Abmarl/abmarl/sim/agent_based_simulation.py", line 220, in agents
    assert type(value_agents) is dict, "Agents must be a dict."
AssertionError: Agents must be a dict.
```

Can we have support for agents to be of type OrderedDict as well?

**Comment by rusu24edward** [comment]
Based on [this](https://realpython.com/python-ordereddict/) and [this](https://stackoverflow.com/questions/34305003/difference-between-dictionary-and-ordereddict), the reasons for using `OrderedDict` vs `dict` are not as strong as they once were. `OrderedDict` has the `move_to_end` command, which can be done with `dict` like so:
```
od.move_to_end('b')  # now it is: OrderedDict([('a', 2), ('b', 1)])
d['b'] = d.pop('b')  # now it is: {'a': 2, 'b': 1}
```
`dicts` in Python 3.8+ have the `reversed` command as well, and if someone is using Python 3.7 they can do the same like so:
```
dict(reversed(list(d.items())))  # {'a': 2, 'b': 1}
```
Abmarl requires Python 3.7+, so the point about reversed may be applicable, but I believe for LC that the default python version is 3.8, so that won't be an issue.

So maybe consider switching to using `dict`?
